### ISSUE TITLE
what compiler should i use to build this?

### ISSUE THREAD

**Issue by 0xh3LL0** [rofl0r/agsutils#1]

**Comment by rofl0r** [comment]
gcc or clang, i guess. or mingw-gcc on winblows...
let me know if you face any issues...

**Comment by 0xh3LL0** [comment]
i prefer mingw, do i need specific version? like 4.7.1 or 5.X.X?

**Comment by rofl0r** [comment]
any will work, since this is C code, not C++ which changes semantics at the blink of an eye...
joking aside, it probably makes sense to get latest mingw just for the sake of having the latest and greatest.

**Comment by 0xh3LL0** [comment]
thanks, i'll try it.
