### ISSUE TITLE
Can`t compile under Winblows What I do wrong

### ISSUE THREAD

**Issue by necros2k7** [rofl0r/agsutils#14]
gcc 8.1,9.2.0
Z:\ags>make
cc   -Wall -Wextra -Wno-unknown-pragmas -Wno-sign-compare -Wno-switch -Wno-unused -Wno-pointer-sign -o ByteArray.o -c ByteArray.c
process_begin: CreateProcess(NULL, cc -Wall -Wextra -Wno-unknown-pragmas -Wno-sign-compare -Wno-switch -Wno-unused -Wno-pointer-sign -o ByteArray.o -c ByteArray.c, ...) failed.
make (e=2): ═х єфрхЄё  эрщЄш єърчрээ√щ Їрщы.
make: *** [Makefile:57: ByteArray.o] Error 2

**Comment by rofl0r** [comment]
it seems you have no binary called `cc`. so maybe you should run `CC=mingw-whatever-gcc make` instead.

**Comment by necros2k7** [comment]
Hm,can`t seem to have any of these in BIN dir
20.02.2019  23:00           108я074 7-zip.chm
22.02.2019  04:00         1я679я360 7z.dll
22.02.2019  04:00           468я992 7z.exe
22.02.2019  04:00           205я824 7z.sfx
22.02.2019  04:00           186я880 7zCon.sfx
27.11.2019  18:16         1я157я632 addr2line.exe
27.11.2019  18:16         1я186я304 ar.exe
27.11.2019  18:16         1я926я656 as.exe
27.11.2019  18:16         1я156я096 c++filt.exe
27.11.2019  21:07         1я204я224 cpp.exe
27.11.2019  18:16         1я218я560 dlltool.exe
27.11.2019  18:16            56я832 dllwrap.exe
27.11.2019  18:16            43я008 elfedit.exe
27.11.2019  21:07         1я205я760 g++.exe
27.11.2019  21:07            63я488 gcc-ar.exe
27.11.2019  21:07            62я976 gcc-nm.exe
27.11.2019  21:07            62я976 gcc-ranlib.exe
27.11.2019  21:07         1я203я200 gcc.exe
27.11.2019  21:07           585я728 gcov-dump.exe
27.11.2019  21:07           646я144 gcov-tool.exe
27.11.2019  21:07           861я184 gcov.exe
27.11.2019  18:55         7я528я448 gdb.exe
27.11.2019  18:55           558я592 gdbserver.exe
27.11.2019  18:16         1я228я288 gprof.exe
27.11.2019  19:02           800я768 grep.exe
27.11.2019  19:04           515я584 jpegtran.exe
27.11.2019  19:04           504я832 lame.exe
27.11.2019  18:16         1я673я216 ld.bfd.exe
27.11.2019  18:16         1я673я216 ld.exe
27.11.2019  19:06           225я280 make.exe
27.11.2019  19:06           225я280 mingw32-make.exe
27.11.2019  18:16         1я170я432 nm.exe
27.11.2019  18:16         1я298я432 objcopy.exe
27.11.2019  18:16         2я575я872 objdump.exe
27.11.2019  21:19           304я640 oggdec.exe
27.11.2019  21:19           889я344 oggenc.exe
27.11.2019  21:19           287я232 ogginfo.exe
27.11.2019  21:07           436я224 optipng.exe
27.11.2019  21:11           630я272 pcre2grep.exe
27.11.2019  21:11         1я890я816 pcre2test.exe
27.11.2019  21:09           519я168 pcregrep.exe
27.11.2019  21:09         1я515я520 pcretest.exe
27.11.2019  21:11           116я224 pngcheck.exe
27.11.2019  18:16         1я186я304 ranlib.exe
27.11.2019  18:16           879я616 readelf.exe
27.11.2019  21:23           266я240 sed.exe
27.11.2019  18:16         1я159я168 size.exe
27.11.2019  18:33           223я744 sort.exe
27.11.2019  18:16         1я158я144 strings.exe
27.11.2019  18:16         1я298я432 strip.exe
27.11.2019  18:33           140я800 uniq.exe
27.11.2019  21:24           879я104 unzstd.exe
27.11.2019  21:19           272я384 vcut.exe
27.11.2019  21:19           287я232 vorbiscomment.exe
27.11.2019  18:33           145я408 wc.exe
27.11.2019  18:16         1я182я720 windmc.exe
27.11.2019  18:16         1я284я096 windres.exe
27.11.2019  21:24           879я104 zstd.exe
27.11.2019  21:24           879я104 zstdcat.exe
27.11.2019  21:24           879я104 zstdmt.exe

Can you possibly please try to compile it in VM in spare time?

**Comment by rofl0r** [comment]
> Can you possibly please try to compile it in VM in spare time?

no, i don't have anything windows. it seems your mingw distribution is C++-only, try to get one that also has a C compiler.

**Comment by necros2k7** [comment]
ok will look into

**Comment by necros2k7** [comment]
yeah I have cc1.exe instead

**Comment by rofl0r** [comment]
i updated windows build instructions in README. tl;dr: you need cygwin, it doesnt work with mingw.

**Comment by rofl0r** [comment]
oops, closed this by accident in a commit that referenced the wrong issue number, which has since been corrected by a forced push.

**Comment by katashi123** [comment]
> i updated windows build instructions in README. tl;dr: you need cygwin, it doesnt work with mingw.

Hello, I try compile with cygwin, but fail
![err](https://user-images.githubusercontent.com/57318233/125550570-dc277748-c688-4177-b0b4-b58bcaff58d4.png)
How to fix it?

**Comment by rofl0r** [comment]
@katashi123 install gcc compiler in the cygwin installer gui

edit: oh, and you need to use the cygwin terminal, not windows cmd.exe
