### ISSUE TITLE
Don't support multiarchive games

### ISSUE THREAD

**Issue by SileNTViP** [rofl0r/agsutils#18]
Hello.
Clib32.c don't change archive file by LibUid.
Example game Zniw Adventure:
ctgame.exe - main Clib archive...
ctgame.001
ctgame.002
...
ctgame.007
File acsprset.spr in ctgame.001 archive... But agstract try extract from ctgame.exe.

**Comment by rofl0r** [comment]
try now.

**Comment by rofl0r** [comment]
@SileNTViP can you confirm whether it works for you now ?

**Comment by SileNTViP** [comment]
> @SileNTViP can you confirm whether it works for you now ?

Yes. It's work now. Thanks,
