### ISSUE TITLE
agsprite Sprite file version 12 support

### ISSUE THREAD

**Issue by jaykup1** [rofl0r/agsutils#25]
agsprite is giving "unsupported sprite file version 12" with 3.6 builds of AGS. Any possible fix?

**Comment by rofl0r** [comment]
that format is very different and i didnt have opportunity yet to implement it, lacking a testgame using the format. if you can point me to one (preferably a small, free one) i can give it a shot.

**Comment by jaykup1** [comment]
Sure. Thank you for keeping this project up and running.

[Tumbleweed](https://github.com/dkrey/ags_tumbleweed)
[3.6 version Windows](https://www.mediafire.com/file/ow204nkk40u5vib/ags_tumbleweed_3.6_windows.rar/file)
[3.6 Project](https://www.mediafire.com/file/8hb0jwvwcatom9o/ags_tumbleweed.rar/file)

**Comment by rofl0r** [comment]
implemented basic support that seems to work with v12 spritecache (at least uncompressed version). i expect that RLE-compressed spritecache may be broken, lzw (de)compression isn't implemented for the time being. in case you know how to tweak those settings, i'd appreciate if you could test with RLE enabled, using both 16 and 32 bit images with less than 256 colors.

**Comment by jaykup1** [comment]
With RLE enabled project it doesn't work at all, uncompressed 16 and 32 bit seems to work with less than 256 colors.
[Test files with AGS 3.6 General Settings screenshots](https://www.mediafire.com/file/rsa0kkvr1qc4qnr/AGSTESTS.rar/file)

**Comment by rofl0r** [comment]
fixed rle eba6ce2...6209c2e - thanks for the testcases. it'd be interesting to see what AGS does for images > 256 colors when RLE is selected.
as for LZW, this remains unimplemented for now. let me know whether you come across any published games making use of it.

**Comment by rofl0r** [comment]
pushed lzw support: e72e23e
