### ISSUE TITLE
Problem extract sprites (Unsupported compression method 3)

### ISSUE THREAD

**Issue by AngelDevIndie** [rofl0r/agsutils#35]
I have a problem when I extract sprites. Prompt shows this message **_"Unsupported compression method 3"_**

The AGS is version 3.6.1.8 and the utils is the last commit.

[Attacth spr file](https://www.mediafire.com/file/aobgbhdmjex734z/acsprset.spr/file)

**Comment by rofl0r** [comment]
AGS commit [028dbe1bb3d74e78affd982488f1b9a0bac3068d](https://github.com/adventuregamestudio/ags/commit/028dbe1bb3d74e78affd982488f1b9a0bac3068d) added a new compression method, deflate, which is the same algorithm used by the aged zip format, so i highly doubt it's more effective than the existing lzw or rle algorithms - especially given that deflate isn't tuned at all for media. either way, this new format was added 1.5 months ago so it's hardly a surprise we don't support it yet. anyway, thanks for bringing this to our attention.

**Comment by rofl0r** [comment]
your testcase (thanks for it) is now properly unpacked by agsprite using git master.
