### ISSUE TITLE
Extracting doesn't work

### ISSUE THREAD

**Issue by SillyconWilly** [rofl0r/agsutils#37]
Hi!

I have tried to extract the files with your extract utility, but I always get an error message. Can you please tell me how I can extract the files from the exe file with your tool?

bye

**Comment by rofl0r** [comment]
1) which exe
2) which error message

**Comment by SillyconWilly** [comment]
Hi!

Thank you for your fast reply. Today I realized that I didn't put all the required files in the folder. I only put the exe file in the folder and got this error message. 

Error Message from yesterday :-)

:::AGStract 0.9.9 by rofl0r:::
error opening mfl datafile test.001
error opening test.exe


Because of the small font in the command line window, I only paid attention to the "error words" and thought that this was related to the admin rights or something else. But what I didn't noticed yesterday is that my game has not only a single exe file but also 2 files behind it. Today I could extract all the files with your tool. Thats great. :-)

Just a short explanation why I asked for your help. Yesterday I tried out the tool "AGS Unpacker" and used it on the game.exe file only. The other both files I just mentioned weren't in the same folder, but the tool unpacked the whole stuff out of this single exe file. So I thought I just need to unpack the exe. I tried the same procedure with your tool and have got that error message. So I decided to use the AGS Unpacker, because I'm not that good with the command line stuff anyway. Then I realized that the repack function of the AGS Unpacker seems not to work. Because without repacking I would be lost, I tried your tools once more and today I managed it finally. But now I have a new question. When I unpacked with your tool I've got 2 files more in the folder than with the AGS Unpacker method. 1 file (agspack.info for repacking) is clear to me but whats about the second file (agspack.exestub)? What exactly is this for? I just tried the repacking too and it worked, but when I repacked with "-e" in the command line I've got all the new and edited stuff in one standalone exe file. And there is all in right? But what should I do with the exe file I created using the repacking command without that "-e"?
So I think thats all for now and I think it's great that you have created all these tools. Sorry for that long text. :-(

bye

    Am Dienstag, 30. Juli 2024 um 22:17:12 MESZ hat rofl0r ***@***.***> Folgendes geschrieben:   

 

   
   - which exe
   - which error message

**Comment by rofl0r** [comment]
agspack.exestub is the exe part of your exe. it's only needed to recreate a working executable from the extracted data. so once you are done with repacking, you can delete it after your modified exe works.
btw if you hit CTRL-F in the README and search for exestub, it's explained there as well.

**Comment by rofl0r** [comment]
in case it still isn't clear, an exe produced by ags actually looks like this:
`[actual exe][game data][footer]`. in other words it's an exe file concatenated with a game data container (think of it like a zip archive), and a small footer that contains the information at which file offset the game data container starts. agstools extracts the exe part as .exestub, and the gamedata into the directory you specified. the exestub is needed so the game can be started with a click, without having to load the game data pack into the standalone AGS engine.

**Comment by SillyconWilly** [comment]
Hi!
Thank you very much for your extensive information. :-)
bye chris
