### ISSUE TITLE
running on Win10x64 WSL (Ubuntu 18.08 image), what I do wrong?

### ISSUE THREAD

**Issue by necros2k7** [rofl0r/agsutils#7]
bash: ./agstract: cannot execute binary file: Exec format error

**Comment by rofl0r** [comment]
where did you get the file from?

**Comment by necros2k7** [comment]
your github releases section

**Comment by rofl0r** [comment]
try this https://0x0.st/zDBL.gz

**Comment by necros2k7** [comment]
thanx a lot it works! pls can you upload other fixed agsutils xept agsex (works fine)? PS. I should install Python2 for agsoptimize right? (/usr/bin/env: ‘python2’: No such file or directory)

**Comment by rofl0r** [comment]
here you go https://0x0.st/zDJl.xz

apparently WSL only supports linux x86_64 binaries. and yes, agsoptimize requires python2 at the moment.
